# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170909_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AddField(
            model_name='post',
            name='detail',
            field=models.ManyToManyField(related_name='Post', to='myapp.Detail'),
        ),
    ]
